### ISSUE TITLE
NameError: name 'Enum' is not defined

### ISSUE THREAD

**Issue by ShelterWFF** [X-PLUG/mPLUG-Owl#167]
Traceback (most recent call last):
  File "/root/anaconda3/envs/mplug_owl/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/root/anaconda3/envs/mplug_owl/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/nanshu_data/jgx/mPLUG-Owl/mPLUG-Owl/serve/web_server.py", line 13, in <module>
    from .gradio_patch import Chatbot as grChatbot
  File "/nanshu_data/jgx/mPLUG-Owl/mPLUG-Owl/serve/gradio_patch.py", line 11, in <module>
    class _Keywords(Enum):
NameError: name 'Enum' is not defined

**Comment by isruihu** [comment]
Same problem. Did you find a solution?

**Comment by tdye24** [comment]
Same problem. Did you find a solution?
