### ISSUE TITLE
ValueError: Tokenizer class MplugOwlTokenizer does not exist or is not currently imported.

### ISSUE THREAD

**Issue by a15097916856** [X-PLUG/mPLUG-Owl#75]
bash：python -m serve.web_server --base-model MAGAer13/mplug-owl-llama-7b --bf16
install flash-attn first.
Downloading (…)rocessor_config.json: 100%|███████████████████████████████████████████████████████████████████████████████████| 163/163 [00:00<00:00, 589kB/s]
Downloading (…)okenizer_config.json: 100%|██████████████████████████████████████████████████████████████████████████████████| 875/875 [00:00<00:00, 3.10MB/s]
Traceback (most recent call last):
  File "/home/lt/anaconda3/envs/mplug/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/lt/anaconda3/envs/mplug/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/lt/model/mPLUG-Owl-main/serve/web_server.py", line 390, in <module>
    model = mPLUG_Owl_Server(
  File "/home/lt/model/mPLUG-Owl-main/serve/model_worker.py", line 41, in __init__
    self.tokenizer = AutoTokenizer.from_pretrained(base_model)
  File "/home/lt/anaconda3/envs/mplug/lib/python3.10/site-packages/transformers/models/auto/tokenization_auto.py", line 699, in from_pretrained
    raise ValueError(
ValueError: Tokenizer class MplugOwlTokenizer does not exist or is not currently imported.

**Comment by MAGAer13** [comment]
Fixed! Try it again.
